# clone repo
# Convert MD to MAML

version: 1.0.{build}
branches:
  only:
    - staging
    - live

install:
  - git clone https://github.com/PowerShell/PowerShell-Docs
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      Install-Module -Name platyPS -Repository PSGallery -Force
      Install-Module -Name Pester -Repository PSGallery -Force
      Import-Module ./tests/AppVeyorTest.psm1

build_script:
  - ps: |
      ./appveyor.ps1

test_script:
  - ps: |
      Invoke-AppveyorTest

artifacts:
  - path: updatablehelp
    name: "<span data-ttu-id=&quot;b02ac-101&quot;>updatablehelp</span><span class=&quot;sxs-lookup&quot;><span data-stu-id=&quot;b02ac-101&quot;>updatablehelp</span></span>"

only_commits:
  files:
    - reference/**/*
    - appveyor.ps1
    - appveyor.yml
    - tests/**/*

deploy:
  - provider: AzureBlob
    name: "<span data-ttu-id=&quot;b02ac-102&quot;>live</span><span class=&quot;sxs-lookup&quot;><span data-stu-id=&quot;b02ac-102&quot;>live</span></span>"
    on:
      branch: live
    storage_account_name: pshelp
    storage_access_key:
      secure: Rk2OPX/IPOix5LKL1oIyp9GjN4lCKVEgpy4eOSL4WMTOFEtOkO7+3Hw8uYCxCXtV728lxtghscOCH2XouPkSyC7fJx99keG2uz9cgBjbH9xiG+3RwXT0+2xvsBOrbYwO
    container: powershell
    folder: help
    artifact: updatablehelp
    unzip: true
    set_content_type: false

  - provider: AzureBlob
    name: "<span data-ttu-id=&quot;b02ac-103&quot;>staging</span><span class=&quot;sxs-lookup&quot;><span data-stu-id=&quot;b02ac-103&quot;>staging</span></span>"
    on:
      branch: staging
    storage_account_name: pshelp
    storage_access_key:
      secure: Rk2OPX/IPOix5LKL1oIyp9GjN4lCKVEgpy4eOSL4WMTOFEtOkO7+3Hw8uYCxCXtV728lxtghscOCH2XouPkSyC7fJx99keG2uz9cgBjbH9xiG+3RwXT0+2xvsBOrbYwO
    container: int-powershell
    folder: help
    artifact: updatablehelp
    unzip: true
    set_content_type: false
